metainfo:
    gender: 'neutral'
    data_dir : haku/
    subject: "haku_clip_spatial_ienc_no_bg"
    start_frame: 0
    end_frame: 50

train:
    type: "Video"
    except_image_id: [2,7,12,17,22]
    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8

    num_sample : 512 

valid:
    type: "VideoVal"
    image_id: 0
    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    num_sample : -1
    pixel_per_batch: 2048 

test:
    type: "VideoTest"
    image_id: [2,7,12,17,22]
    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    num_sample : -1
    pixel_per_batch: 2048